default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: postgres

development:
  <<: *default
  database: budget_categorizer_development

test:
  <<: *default
  database: budget_categorizer_test

production:
  <<: *default
  database: budget_categorizer_production
  username: budget_categorizer
  password: <%= ENV["BUDGET_CATEGORIZER_DATABASE_PASSWORD"] %>
